### ISSUE TITLE
您好，我在使用框架的过程中遇到已下报错

### ISSUE THREAD

**Issue by xxzgithub** [Achenglove/PictureSelector#1]
2021-06-24 15:31:57.883 7545-7545/com.qzh. E/TAG: url = http://111.203.232.175:8085/null
2021-06-24 15:31:57.883 7545-7545/com.qzh. E/TAG: url = http://111.203.232.175:8085/null
2021-06-24 15:31:57.902 1528-2749/? E/Parcel: Class not found when unmarshalling: com.luck.picture.lib.entity.LocalMedia
    java.lang.ClassNotFoundException: com.luck.picture.lib.entity.LocalMedia
        at java.lang.Class.classForName(Native Method)
        at java.lang.Class.forName(Class.java:454)
        at android.os.Parcel.readParcelableCreator(Parcel.java:3031)
        at android.os.Parcel.readParcelable(Parcel.java:2981)
        at android.os.Parcel.readValue(Parcel.java:2883)
        at android.os.Parcel.readListInternal(Parcel.java:3324)
        at android.os.Parcel.readArrayList(Parcel.java:2467)
        at android.os.Parcel.readValue(Parcel.java:2904)
        at android.os.Parcel.readArrayMapInternal(Parcel.java:3261)
        at android.os.BaseBundle.initializeFromParcelLocked(BaseBundle.java:292)
        at android.os.BaseBundle.unparcel(BaseBundle.java:236)
        at android.os.BaseBundle.getString(BaseBundle.java:1160)
        at android.content.Intent.getStringExtra(Intent.java:8552)
        at com.android.server.wm.ActivityStarter.startActivity(ActivityStarter.java:847)
        at com.android.server.wm.ActivityStarter.startActivity(ActivityStarter.java:732)
        at com.android.server.wm.ActivityStarter.startActivityMayWait(ActivityStarter.java:2070)
        at com.android.server.wm.ActivityStarter.execute(ActivityStarter.java:646)
        at com.android.server.wm.ActivityTaskManagerService.startActivityAsUser(ActivityTaskManagerService.java:1717)
        at com.android.server.wm.ActivityTaskManagerService.startActivityAsUser(ActivityTaskManagerService.java:1613)
        at com.android.server.wm.ActivityTaskManagerService.startActivity(ActivityTaskManagerService.java:1566)
        at android.app.IActivityTaskManager$Stub.onTransact(IActivityTaskManager.java:1737)
        at android.os.Binder.execTransactInternal(Binder.java:1056)
        at android.os.Binder.execTransact(Binder.java:1029)
     Caused by: java.lang.ClassNotFoundException: com.luck.picture.lib.entity.LocalMedia
        at java.lang.Class.classForName(Native Method) 
        at java.lang.Class.forName(Class.java:454) 
        at android.os.Parcel.readParcelableCreator(Parcel.java:3031) 
        at android.os.Parcel.readParcelable(Parcel.java:2981) 
        at android.os.Parcel.readValue(Parcel.java:2883) 
        at android.os.Parcel.readListInternal(Parcel.java:3324) 
        at android.os.Parcel.readArrayList(Parcel.java:2467) 
        at android.os.Parcel.readValue(Parcel.java:2904) 
        at android.os.Parcel.readArrayMapInternal(Parcel.java:3261) 
        at android.os.BaseBundle.initializeFromParcelLocked(BaseBundle.java:292) 
        at android.os.BaseBundle.unparcel(BaseBundle.java:236) 
        at android.os.BaseBundle.getString(BaseBundle.java:1160) 
        at android.content.Intent.getStringExtra(Intent.java:8552) 
        at com.android.server.wm.ActivityStarter.startActivity(ActivityStarter.java:847) 
        at com.android.server.wm.ActivityStarter.startActivity(ActivityStarter.java:732) 
        at com.android.server.wm.ActivityStarter.startActivityMayWait(ActivityStarter.java:2070) 
        at com.android.server.wm.ActivityStarter.execute(ActivityStarter.java:646) 
        at com.android.server.wm.ActivityTaskManagerService.startActivityAsUser(ActivityTaskManagerService.java:1717) 
        at com.android.server.wm.ActivityTaskManagerService.startActivityAsUser(ActivityTaskManagerService.java:1613) 
        at com.android.server.wm.ActivityTaskManagerService.startActivity(ActivityTaskManagerService.java:1566) 
        at android.app.IActivityTaskManager$Stub.onTransact(IActivityTaskManager.java:1737) 
        at android.os.Binder.execTransactInternal(Binder.java:1056) 
        at android.os.Binder.execTransact(Binder.java:1029) 
请是什么原因造成的，怎么解决呢？

**Comment by Achenglove** [comment]
忽略混淆就好，或者添加混淆代码，看文章最后

**Comment by xxzgithub** [comment]
好的，感谢
